### ISSUE TITLE
Adding a new emulator?

### ISSUE THREAD

**Issue by DizzzyAllDay** [likeich/console-launcher#18]
### _I would label this as a question rather than an issue but I can't figure out how.. sorry.. but I still love the app 🫶_ 
_i have a picture as well with a the file types it can use-_
![Screenshot_20241126-203545](https://github.com/user-attachments/assets/37502d1c-fce4-475a-8bc4-f52787b62f05)
Thank you for taking the time to read this 🙇

**Comment by likeich** [comment]
Did you pay for this? It just looks like a clone of Lemuroid (which is free) https://play.google.com/store/apps/details?id=com.swordfish.lemuroid&hl=en_US

**Comment by DizzzyAllDay** [comment]
I may have... 🥲, but if your recommending Lemuroid would it be okay if you could get that in frontend instead of what I asked (I just like the simplicity of the Lemuroid/FullRoid allot) and it would be cool if it works alongside ConsoleLauncher! (Thank you as well for telling me about Lemuroid!🫶)

**Comment by likeich** [comment]
I would love to add it but lemuroid does not support frontends sadly.

**Comment by DizzzyAllDay** [comment]
Sadness 🫠 but thank you for telling me! 🙏

**Comment by DizzzyAllDay** [comment]
Apon further research on retro Arch it can work just lots of tweaking around but its kinda fun I'll have to do some more fiddling around with everything but I like everything about this app and I appreciate that I found it, keep up the good work🫶
