### ISSUE TITLE
"No game found" if you try to download icons from SteamGridDB

### ISSUE THREAD

**Issue by piersandro** [likeich/console-launcher#4]
If I try to download updated icons for installed applications (both Better xCloud shortcuts and Android games), a 'No game found' alert is displayed

https://github.com/likeich/console-launcher/assets/19996309/ebd3aee0-1ed9-4776-9f80-5a0673f75d49

Problem encountered with the latest [v112.0.0-alpha8](https://github.com/likeich/console-launcher/releases/tag/v112.0.0-alpha8) release. Previously used the Play Store stable and it worked regularly.

**Comment by likeich** [comment]
Fixed in the latest update (alpha 9)
